"""
Script TOP Callbacks — Rest Position Texture Generator

Generates a 1024x1024 RGBA float32 texture mapping each splat's uniqueID
to its rest position. Only regenerates when the "Regenerate" pulse parameter
is triggered (or on first cook). The result is cached in storage so
subsequent cooks replay the stored texture without recomputing.

No Cache TOP needed downstream — this operator IS the cache.
"""

import numpy



def onPulse(par: Par):
	if par.name == 'Regenerate':
		scriptOp = par.owner
		scriptOp.storage['dirty'] = True
		scriptOp.cook(force=True)


def onCook(scriptOp):
	import numpy as np

	dirty = scriptOp.storage.get('dirty', True)  # True on first cook
	cached = scriptOp.storage.get('pixels', None)

	if not dirty and cached is not None:
		scriptOp.copyNumpyArray(cached)
		return
	
	pop = op('/GaussianSplatting/GaussianSplatPOP/null1')
	positions = pop.points('P')
	uniqueIDs = pop.points('uniqueID')

	texSize = 1024
	numPoints = len(positions)

	pixels = np.zeros((texSize, texSize, 4), dtype=np.float32)

	for i in range(min(numPoints, texSize * texSize)):
		uid = int(uniqueIDs[i])
		if uid >= texSize * texSize:
			continue
		x = uid % texSize
		y = uid // texSize
		pos = positions[i]
		pixels[y, x, 0] = pos[0]  # X
		pixels[y, x, 1] = pos[1]  # Y
		pixels[y, x, 2] = pos[2]  # Z
		pixels[y, x, 3] = 1.0

	scriptOp.storage['pixels'] = pixels
	scriptOp.storage['dirty'] = False
	scriptOp.copyNumpyArray(pixels)
	print(f"Rest positions: {numPoints} points written by uniqueID")


def onGetCookLevel(scriptOp: scriptTOP) -> CookLevel:
	return CookLevel.AUTOMATIC

def onSetupParameters(scriptOp):
	"""Auto-generated by Component Editor"""
	# manual changes to anything other than parJSON will be	# destroyed by Comp Editor unless doc string above is	# changed

	TDJSON = op.TDModules.mod.TDJSON
	parJSON = """
	{
		"Custom": {}
	}
	"""
	parData = TDJSON.textToJSON(parJSON)
	TDJSON.addParametersFromJSONOp(scriptOp, parData, destroyOthers=True)